### ISSUE TITLE
Shimmer using wrong package for deploy

### ISSUE THREAD

**Issue by devindran** [Squirrel/OldSquirrelForWindows#233] opened 2014-01-16 09:47 UTC
I'm not sure if this is a bug or if I'm doing something wrong.

I have installed Microsoft.AspNet.SignalR.Client using NuGet. The package gets created with 3 folders in it.

net40
net45
portable-net45+sl5+netcore45+wp8

My project references net45's dll. The code runs correctly when I debug it. However, I found out that when I used Shimmer to package the app, the eventual installer uses the dll from the portable-net45+sl5+netcore45+wp8 folder.

Although the dlls have the same version, the net45 build is 130kb, while the portable build is 108kb. My installation folder contains the 108kb file.

If I were to replace the dll manually, my installed app works correctly.

I've tried to delete this folder in the package, edit the package's nuspec file, add a <file> reference to my project's nuspec file, disabled any auto package refresh options, but somehow this folder keeps reappearing when I deploy the app.

Is there something in Shimmer that is confusing the correct dll to use?

I've had trouble migrating to Squirrel which is why I'm still on Shimmer.

**Comment by devindran** [comment] 2014-01-18 16:01
After not getting it to work, my workaround was to remove the package entirely and just reference the dll directly in the nuspec file. Without the package there, it doesn't get a chance to go hunting for the wrong folder. 

Appreciate it if someone could verify that this is not only happening to me.

**Comment by flagbug** [comment] 2014-01-18 20:33
Yeah, Squirrel doesn't handle assemblies with multiple framework targets very well currently.
I dug deep into the NuGet.Core code to find how they are doing it, but sadly I wasn't succesful.

**Comment by shiftkey** [comment] 2014-03-23 03:07
Duplicate of #39, let's discuss it over there...

**Closed as completed by shiftkey** 2014-03-23 03:07 UTC
