### ISSUE TITLE
Easy example WPF

### ISSUE THREAD

**Issue by riccardobecker** [Squirrel/OldSquirrelForWindows#44] opened 2013-04-11 14:48 UTC
Hi there,

love the way Shimmer should work only good documentation is missing. I am working on a WPF application that needs to be updated when a new version is ready.

regards

**Comment by haacked** [comment] 2013-04-11 17:25
Yeah, we really need to improve the documentation. Would you be interested in helping out? I'm sure we can discuss areas we need help and provide help.

**Comment by Folcon** [comment] 2013-04-11 19:14
I'm interested in this as well Phil, I've modified `Create-Release.ps1` (https://gist.github.com/Folcon/5366261) and still just a few steps away from getting it working. I've added `EchoArgs.exe` (from the PowerShell Community Extensions - http://pscx.codeplex.com) to help debug it. One of my issues stems from the fact that the pathing seems to be failing. If there are spaces in the path or if anything resides on a network share and thus the path is of the form `//share/something/file.exe` then it can fail. The current issue I have is that the `ApplicationVersion` has to be of the form `1.0.0-alpha` or `1.0.0-b`. Essentially using semantic versioning. But I'm trying to get visual studio and  teamcity to agree so that neither of them reject the build as the `ApplicationVersion` format is incorrect. I'm willing to put some time as well into this effort.

My workaround was explicitly passing the Version:
`.nuget\NuGet pack .\Project\Project.csproj -Build -Properties Configuration=Release -Version 1.0.1-alpha`
`Create-Release Project`

**Comment by riccardobecker** [comment] 2013-04-12 08:33
Hi guys, it's more like getting the whole thing running :-) There is no tutorial whatsoever and the code is quite complex.

**Comment by haacked** [comment] 2013-04-12 21:55
@Folcon The pathing issue? Did you file an issue on that? I'm betting we're not properly quoting the path somewhere. We should always be doing that.

**Comment by anaisbetts** [comment] 2013-04-13 02:18
> Hi guys, it's more like getting the whole thing running :-) There is no tutorial whatsoever and the code is quite complex.

Hey guys, this isn't finished yet - once it is, there will _totally_ be way more documentation and it'll be much more straightforward.

**Comment by Folcon** [comment] 2013-04-13 02:24
@Haacked no I haven't actually, I thought I was misusing it, my gist version seems to work on my local machine and the server which uses share paths, but I'm not certain it's completely safe just yet.

@xpaulbettsx That's fine Paul, more seeing if there was any obvious things that I'm missing, I suspect I'm missing a trick with the semantic versioning for example. Not to mention why my setup.exe can't work out what dispatch context it should be using.

**Comment by cguedel** [comment] 2013-07-18 08:58
@xpaulbettsx Can you clarify the "this isn't finished yet" statement a little? Is this code ready to use or not?

(I was able to create a setup.exe, but it crashes when I start it)

**Comment by anaisbetts** [comment] 2013-07-19 04:18
> Can you clarify the "this isn't finished yet" statement a little? Is this code ready to use or not?

It is not currently ready to use as-is, but we'll be starting work on this again very soon (GitHub has hired someone to work on this full-time)

**Comment by matteomigliore** [comment] 2013-08-27 21:24
Hi! Any news?

Is there someone to chat with about a WPF sample? I can help to produce the documentation when I understand how Shimmer works :).

I need it for a real-world project.

**Comment by shiftkey** [comment] 2013-08-29 23:44
I'm working on a couple of demo apps here:
- https://github.com/shiftkey/TestApp
- https://github.com/shiftkey/play-windows

But all I've been doing so far is running through the [QuickStart](https://github.com/github/Shimmer/wiki/QuickStart) steps against an existing app. It shouldn't be rocket science to get started with Shimmer.

**Comment by matteomigliore** [comment] 2013-08-30 16:21
Hi Brendand, I'm trying your samples.

The TestApp creates the Setup.exe but when I launch it show an error in the
WPF application,
and I don't understand where the UI for the installation is defined.

In the QuickStart you should write, as first step:
- Enable Nuget Package Restore

Then, installing the Shimmer package should include the .nuspec file into
the project,
now it is included as file but not showed in Visual Studio, I've to add it
manually.

I wrote here because I don't know if I can change the QuickStart page and
where I can
create the issues about TestApp and Play Windows.

Thanks!
Matteo

**Comment by shiftkey** [comment] 2013-08-30 23:55
> The TestApp creates the Setup.exe but when I launch it show an error in the WPF application, and I don't understand where the UI for the installation is defined.

I'm not clear here on which part is the issue:
- the TestApp itself, which is WPF
- the installer, which is also WPF

> In the QuickStart you should write, as first step:
> - Enable Nuget Package Restore

Added

> Then, installing the Shimmer package should include the .nuspec file into the project, now it is included as file but not showed in Visual Studio, I've to add it manually.

Captured as issue #69

**Comment by matteomigliore** [comment] 2013-08-31 06:06
> I'm not clear here on which part is the issue:
> 
> the TestApp itself, which is WPF

The TestApp works.

> the installer, which is also WPF

The installer doesn't work, I obtain the message "Failed to install the application".
I followed the "Getting started" with a new project and I obtain the same error.

Other to this I've two questions:
- is there something that explains how to customize the installer UI (a preview waiting fot the "official section")?
- is there something that explains how to use the update system? Where specify the server URL, what publish, where and so on?

**Comment by shiftkey** [comment] 2013-08-31 06:22
> I installer doesn't, I obtain the message "Failed to install the application".
> I follwed the "Getting started" with a new project and I obtain the same error.

Can you share the contents of the log files in `%APPDATA%\Shimmer` - these should help me to diagnose what's happening. 

> is there something that explains how to customize the installer UI (a preview waiting fot the "official section")?

I'm focusing on the core install and update experience at the moment, so I haven't had a chance to exercise and document that. But this is the milestone: https://github.com/github/Shimmer/milestones/0-9-building-a-custom-installer 

> is there something that explains how to use the update system? Where specify the server URL, what publish, where and so on?

Updates are explained here: https://github.com/github/Shimmer/wiki/How-do-updates-work%3F

Hosting is relatively straightfoward but not written up. You can either:
- host the files in a folder on disk or network share (what I've been testing currently)
- any webserver that can serve static files - the URL is just the folder where the contents are hosted

**Comment by matteomigliore** [comment] 2013-08-31 06:34
> I installer doesn't, I obtain the message "Failed to install the application".
> I follwed the "Getting started" with a new project and I obtain the same error.
> Can you share the contents of the log files in %APPDATA%\Shimmer - these should help me to diagnose what's happening.

Yes, this is the error:
System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at ReactiveUIMicro.AwaitableAsyncSubject`1.GetResult()
   at Shimmer.Client.InstallManager.<executeInstall>d__6.MoveNext()

The same error for my project.

> is there something that explains how to customize the installer UI (a preview waiting fot the "official section")?
> I'm focusing on the core install and update experience at the moment, so I haven't had a chance to exercise and document that. But this is the milestone: https://github.com/github/Shimmer/milestones/0-9-building-a-custom-installer
> 
> is there something that explains how to use the update system? Where specify the server URL, what publish, where and so on?
> Updates are explained here: https://github.com/github/Shimmer/wiki/How-do-updates-work%3F

Great, sorry, I didn't see before.

> Hosting is relatively straightfoward but not written up. You can either:
> 
> host the files in a folder on disk or network share (what I've been testing currently)
> any webserver that can serve static files - the URL is just the folder where the contents are hosted

Ok, so is possible to use a URL also.

**Comment by shiftkey** [comment] 2013-08-31 06:36
> Yes, this is the error:
> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)

I'm looking at this one right now too. Should be fixed in the next release.

> Ok, so is possible to use a URL also.

Correct

**Comment by flagbug** [comment] 2013-08-31 18:09
I've got a similiar error that crashes the installer:

```
ERROR | 2013-08-31 01:54:17  +02 | WixUiBootstrapper: Something unexpected happened:  
System.InvalidOperationException: Sequence contains more than one matching element
   at ReactiveUIMicro.AwaitableAsyncSubject`1.GetResult()
   at Shimmer.Client.InstallManager.<executeInstall>d__6.MoveNext()
```

Steps to reproduce: 
1. Install the application
2. Install the application with the same Setup.exe and version, without removing the previous version

**Comment by shiftkey** [comment] 2013-09-01 03:50
@flagbug @matteomigliore 

Here's a snippet of what's going on under the hood (next release will have these diagnostics):

```
INFO | 2013-09-01 01:48:31 PM +10 | InstallManager: The checking of releases completed - and there was much rejoicing
INFO | 2013-09-01 01:48:31 PM +10 | InstallManager: HEY! We should be applying update TestApp-1.2.0-beta-delta.nupkg
INFO | 2013-09-01 01:48:31 PM +10 | InstallManager: HEY! We should be applying update TestApp-1.3.0-beta-delta.nupkg
WARN | 2013-09-01 01:48:31 PM +10 | Utility: The file C:\Users\brendanforster\AppData\Local\Temp\{5d7da5b9-9ca1-45d5-ba40-b426a6f21aa6}\.ba1\TestApp-1.2.0-beta-delta.nupkg does not exist
WARN | 2013-09-01 01:48:31 PM +10 | Utility: The file C:\Users\brendanforster\AppData\Local\Temp\{5d7da5b9-9ca1-45d5-ba40-b426a6f21aa6}\.ba1\TestApp-1.3.0-beta-delta.nupkg does not exist
ERROR | 2013-09-01 01:48:31 PM +10 | UpdateManager: File C:\Users\brendanforster\AppData\Local\TestApp\packages\TestApp-1.2.0-beta-delta.nupkg should exist but doesn't
ERROR | 2013-09-01 01:48:31 PM +10 | UpdateManager: File C:\Users\brendanforster\AppData\Local\TestApp\packages\TestApp-1.3.0-beta-delta.nupkg should exist but doesn't
ERROR | 2013-09-01 01:48:31 PM +10 | WixUiBootstrapper: Something unexpected happened: System.Exception: Checksummed file doesn't exist: C:\Users\brendanforster\AppData\Local\TestApp\packages\TestApp-1.2.0-beta-delta.nupkg
   at ReactiveUIMicro.AwaitableAsyncSubject`1.GetResult()
   at Shimmer.Client.InstallManager.<executeInstall>d__6.MoveNext()
```

I'm covering this in #70

**Comment by shiftkey** [comment] 2013-09-25 02:07
Right, so I've finally gotten this sample to a point where it covers installation and updating.

https://github.com/shiftkey/Shimmer.Samples

Feel free to send improvements to the demo app (I'll look to add features to it over the next few weeks as I work through it).

If there are things you'd like to see done in terms of samples, raise them as issues over there.

**Closed as completed by shiftkey** 2013-09-25 02:07 UTC
Labels: must have
