### ISSUE TITLE
Creating the package doesn't work when there is a space in directory

### ISSUE THREAD

**Issue by michaelsync** [Squirrel/OldSquirrelForWindows#83] opened 2013-09-02 10:24 UTC
Hello,

I think "New-Release -Project ConsoleApplication6" doesn't work when path has a space.

PM> New-Release -Project ConsoleApplication6
Shimmer: Publishing release for project ConsoleApplication6
Shimmer: Creating Release for C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6 => C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\Releases

Found package C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\bin\Release\ConsoleApplication6.1.0.0.0-beta.nupkg
Full release file at C:\Users\michael.sync\Documents\Visual
Running candle.exe
candle.exe : error CNDL0103 : The system cannot find the file 'Studio' with type 'Source'.
Running light.exe
light.exe : error LGHT0103 : The system cannot find the file 'C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\bin\Release\template.wixobj' 
with type 'Source'.

**Comment by flagbug** [comment] 2013-09-02 10:26
Are you using the latest version? This should have been fixed with https://github.com/github/Shimmer/pull/72

**Comment by michaelsync** [comment] 2013-09-02 10:29
I just changed the version and tested it again. I got different error. 

```
PM> New-Release -Project ConsoleApplication6
Shimmer: Publishing release for project ConsoleApplication6
Shimmer: Checking C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\bin\Release\ for packages

Shimmer: Found package C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\bin\Release\ConsoleApplication6.1.0.0.0-beta.nupkg

Shimmer: Publishing artifacts to C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\Releases
CreateReleasePackage.exe : 
At C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\packages\Shimmer.0.6.10-beta\tools\commands.psm1:63 char:26
+         $releaseOutput = & $createReleasePackageExe -o $releaseDir -p $packageDi ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception: 
System.InvalidOperationException: Source sequence doesn't contain any elements.
   at System.Linq.EnumerableExtensions.ExtremaBy[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, Func`3 compare)
   at CreateReleasePackage.Program.Main(String[] args)



Shimmer: Full release: C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\Releases\ConsoleApplication6-1.0.0.0-beta-full.nupkg
Shimmer: Delta release: 

Shimmer: Creating installer for C:\Users\michael.sync\Documents\Visual Studio 2012\Projects\ConsoleApplication6\Releases\ConsoleApplication6-1.0.0.0-beta-full.nupkg
Shimmer: Running candle.exe
Windows Installer Xml Compiler version 3.6.3303.0
Copyright (C) Outercurve Foundation. All rights reserved.

template.wxs
Shimmer: Running light.exe
Windows Installer Xml Linker version 3.6.3303.0
Copyright (C) Outercurve Foundation. All rights reserved.

PM> 
```

**Comment by michaelsync** [comment] 2013-09-02 10:30
The version that I just tested is 0.6.10-beta.

**Comment by michaelsync** [comment] 2013-09-02 10:34
ok. I would say that it might be diff issue. I tested in diff path that doesn't have any space but got the same error.

**Comment by michaelsync** [comment] 2013-09-02 10:35
I got "CreateReleasePackage has stopped working" error.

**Comment by flagbug** [comment] 2013-09-02 11:24
Seems like the problem was introduced in 0.6.10

**Comment by shiftkey** [comment] 2013-09-02 11:24
I wonder if this is related to having a fresh `RELEASE` file

**Comment by shiftkey** [comment] 2013-09-02 11:37
Confirmed: for some reason I'm just blindly assuming the RELEASES file has stuff.

I'll push a fix now which will check that.

**Comment by shiftkey** [comment] 2013-09-02 11:50
I've pushed `0.6.11` which does that sanity check for an empty `RELEASES` file. Let me know if it's still happening on your end.

https://www.nuget.org/packages/Shimmer/0.6.11-beta

**Comment by flagbug** [comment] 2013-09-02 12:00
Nope, the error still occurs.

My `RELEASES` file:
`61E8CAE95BDA1C94A79F06FF3D088790B6A862C9 Espera-1.7.6-beta-full.nupkg 4618858`

On an empty release directory, the initial `New-Release` works fine, but all subsequent give the above error.

Funny thing is: The releases are actually created fine, my `RELEASES` file looks afterwards like this, even though the console said an exception was thrown and the `CreateReleasePackage.exe`crashed:

```
BD450EC2A780045E1059D05D3300EE97EB0A455E Espera-1.7.7-beta-delta.nupkg 53211
61E8CAE95BDA1C94A79F06FF3D088790B6A862C9 Espera-1.7.6-beta-full.nupkg 4618858
D7C07DBD900E2D58430AE8FAE35655947F80A66E Espera-1.7.7-beta-full.nupkg 4618860
```

**Comment by flagbug** [comment] 2013-09-02 12:13
@shiftkey I hope this helps:

![](http://i.imgur.com/MN1rtp5.png)

EDIT: It fails at line 40 where it tries compare the versions, but `x.Version = 1.7.6` and `package.Version` is also 1.7.6, even though my AssemblyInfo version is 1.7.7

EDIT EDIT: Aha! It seems that this is related to https://github.com/github/Shimmer/issues/58 where it fails when the build directory has multiple .nupkg files with different version numbers

**Comment by shiftkey** [comment] 2013-09-02 13:18
Right, I don't like MaxBy in there - let's see if i can kill that off and catch this as a regression...

**Closed as completed** 2013-09-02 23:53 UTC
Labels: bug

**Comment by michaelsync** [comment] 2013-09-03 00:51
Thanks guys! I will check it out.

**Comment by shiftkey** [comment] 2013-09-03 00:54
Version `0.6.12` has these changes

**Comment by michaelsync** [comment] 2013-09-03 07:55
thanks! I just tested and it works.
