### ISSUE TITLE
Install-Package Squirrel.Client does not generate .nuspec file

### ISSUE THREAD

**Issue by kerams** [Squirrel/OldSquirrelForWindows#246] opened 2014-04-03 20:20 UTC
As per the QuickStart guide, I have run
`Install-Package Squirrel.Client -Project TestApp`
in a clean solution with a single WPF project created solely for testing. There were no errors and all references appeared in the solution. However, the .nuspec file is not automatically opened in VS and I can't find it in any folder.
Lastly, running `New-Release` results in the following error:
`The term 'New-Release' is not recognized as the name of a cmdlet, function, script file, or operable program.`

I am using VS 2013, .NET 4.5 and the latest NuGet.

**Comment by bgrainger** [comment] 2014-04-04 18:18
I've come back to an existing Squirrel-based project after a few months, and am getting the same error when trying to run `New-Release`. I don't remember everything that's changed in the meantime, but I have at least upgraded the installed version of NuGet (in VS > Tools > Extensions and Updates).

When I run the command, Process Monitor shows that devenv is searching all directories in my path for `New-Release.ps1` and `New-Release.psm1`; Search Everything shows that I have no files on my disk named `New-Release.*`

I see that `New-Release` is defined in [visualstudio.psm1](https://github.com/Squirrel/Squirrel.Windows/blob/master/src/CreateReleasePackage/tools/visualstudio.psm1), but I have no idea how to get that script loaded in the Package Manager Console.

**Comment by stefanolson** [comment] 2014-04-07 18:54
It is working for me in visual studio 2013 update 2 RC (ie, the latest version of visual studio)

**Comment by kerams** [comment] 2014-04-08 12:30
I've just tried it with Update 2, but it has unsurprisingly (since Squirrel should already work on VS 2012 onwards) failed to resolve my issue. I feel like something very obvious is amiss.

**Comment by jittuu** [comment] 2014-04-16 07:17
The same issue for me as well, and I'm using:
- VS2013 Update 2 RC
- Nuget 2.8.50313.46

**Comment by bradphelan** [comment] 2014-04-23 08:18
Same for me. No nuspec file and no New-Release command. My install is the following

```
Microsoft Visual Studio Professional 2013
Version 12.0.30110.00 Update 1
Microsoft .NET Framework
Version 4.5.50938

Installed Version: Professional

LightSwitch for Visual Studio 2013   06177-004-0444002-02934
Microsoft LightSwitch for Visual Studio 2013

Microsoft Office Developer Tools for Visual Studio 2013 ENU   06177-004-0444002-02934
Microsoft Office Developer Tools for Visual Studio 2013 ENU

Team Explorer for Visual Studio 2013   06177-004-0444002-02934
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0444002-02934
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0444002-02934
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0444002-02934
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0444002-02934
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0444002-02934
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

AnkhSVN - Subversion Support for Visual Studio   2.5.12440.9
AnkhSVN - Subversion Support for Visual Studio 2.5.12440.9 
 * Ankh.Package 2.5.12440.9
 * Subversion 1.8.8 via SharpSvn 1.8008.3178.19

SharpSvn is linked to: Apr 1.5.0, Apr-util 1.5.3, Cyrus Sasl 2.1.25, eXpat 2.0.1, OpenSSL 1.0.1g 7 Apr 2014, serf 1.3.4, SQLite 3.7.17, Subversion 1.8.8-SharpSvn-1.8.8, ZLib 1.2.8
SharpSvn is optionally linked to: Berkeley DB 4.4.20, SharpPlink 1.8008.3178.19

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.0.11213.0
For additional information, visit http://www.asp.net/

Color Theme Designer   1.0
Designer for creating new color themes

Common Azure Tools   1.0
Provides common services for use by Azure Mobile Services and Windows Azure Tools.

JetBrains ReSharper 8.2   C# Edition build 8.2.0.2160 on 2014-03-20T17:53:08
JetBrains ReSharper 8.2 package for Microsoft Visual Studio. For more information about ReSharper, visit http://www.jetbrains.com/resharper/. Copyright © 2003–2014 JetBrains, Inc.

Microsoft Web Developer Tools 2013   2.0.40926.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Windows Azure Web Sites
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Windows Azure

NuGet Package Manager   2.8.50313.46
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   12.0.30919.1
Microsoft SQL Server Data Tools

Windows Azure Mobile Services Tools   1.0
Windows Azure Mobile Services Tools

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.
```

**Comment by jittuu** [comment] 2014-04-23 08:38
I think squirrel transition is still in progress as of #211. we need to use [Shimmer](http://www.nuget.org/packages/Shimmer/) package for now. More info at this [Bradley Grainger's gist](https://gist.github.com/bgrainger/7287703)

**Comment by arlair** [comment] 2014-06-03 17:43
I get the same problem.
VS 2012 Update 4
Nuget 2.8.50313.31

**Comment by bgrainger** [comment] 2014-06-09 21:20
I really wanted to ship an update, so I came back to my project and figured out how to get it working.
1. Squirrel appears to be incompatible with NuGet Automatic Package Restore; I had to [revert that commit](https://github.com/bgrainger/GitBlame/commit/e2667ee0416d2463988c458f8ed5912ac283c2c1) to get Squirrel working.
2. Clone the latest `Squirrel.Windows` code.
3. Revert 77c11df685498cb19729188325ba2297a3970fc1; this causes an infinite loop when running `New-Release`.
4. Build Squirrel.Windows.
5. Create a new folder, e.g., `C:\Squirrel`.
6. Copy `Squirrel.Windows\bin\*.*` to `C:\Squirrel`.
7. Copy `Squirrel.Windows\src\CreateReleasePackage\tools\*.*` to `C:\Squirrel`.
8. Copy `Squirrel.Windows\ext\wix` to `C:\Squirrel\wix\*.*` (there must be a `wix` subfolder).
9. In Visual Studio (with your solution open), open the Package Manager Console window and run `Import-Module C:\Squirrel\visualstudio.psm1`.
10. Now you can run `New-Release -Project YourProject` and it should successfully build the NuGet packages and installer.

BTW, when I tried updating the previous version of my app to the latest (generated via this procedure), installing the delta package failed, and Squirrel just gave up (instead of falling back to the full package). I don't know if this was just a local problem, but I'm now deleting the delta packages before publishing, as a precaution.

**Comment by stefanolson** [comment] 2014-06-18 20:37
@bgrainger, your delta issue is caused by a problem with extracting the Delta. It should go to the full if the Delta fails, but the exception isn't handled within squirrel, thus it can't fall back.  The issue has been reported here 
https://github.com/Squirrel/Squirrel.Windows/issues/236

Stefan

**Comment by leorin** [comment] 2014-06-30 15:40
Any fix for this problem? I want to use Squirrel:(

**Comment by christianrondeau** [comment] 2014-07-28 23:12
Same issue, with both Visual Studio 2013 Professional Update 2 and Visual Studio Express 2013 Update 2, with NuGet 2.8.50313.46. No nuspec file was created, and the Package Manager console only shows dependency installations.

**Comment by arlair** [comment] 2014-09-02 16:21
Just as a heads up, it seems like this Squirrel is road kill and work appears to be focused here on a cut down version:
https://github.com/Squirrel/Squirrel.Windows.Next

**Closed as completed** 2015-01-05 11:08 UTC
